export const GET_GENRES_SUCCESS = "GET_GENRES_SUCCESS";
export const GET_GENRES_ERROR = "GET_GENRES_ERROR";
export const GET_GENRES_REQUEST = "GET_GENRES_REQUEST";
export const ADMIN_GENRE_REQUEST = "ADMIN_GENRE_REQUEST"
export const ADMIN_GENRE_SUCCESS = "ADMIN_GENRE_SUCCESS"
export const ADMIN_GENRE_FAIL = "ADMIN_GENRE_FAIL"

export const DELETE_GENRE_REQUEST = "DELETE_GENRE_REQUEST"
export const DELETE_GENRE_FAIL = "DELETE_GENRE_FAIL"
export const DELETE_GENRE_SUCCESS = "DELETE_GENRE_SUCCESS"

export const DELETE_GENRE_RESET = "DELETE_GENRE_RESET"



export const CLEAR_ERRORS = "CLEAR_ERRORS" 