export const ALL_MOVIE_REQUEST = "ALL_MOVIE_REQUEST"
export const ALL_MOVIE_SUCCESS = "ALL_MOVIE_SUCCESS"
export const ALL_MOVIE_FAIL = "ALL_MOVIE_FAIL"

export const NEW_MOVIE_REQUEST = "NEW_MOVIE_REQUEST"
export const NEW_MOVIE_SUCCESS = "NEW_MOVIE_SUCCESS"
export const NEW_MOVIE_FAIL = "NEW_MOVIE_FAIL"

export const NEW_MOVIE_RESET = "NEW_MOVIE_RESET "

export const DELETE_MOVIE_REQUEST = "DELETE_MOVIE_REQUEST"
export const DELETE_MOVIE_SUCCESS = "DELETE_MOVIE_SUCCESS"
export const DELETE_MOVIE_FAIL = "DELETE_MOVIE_FAIL"
export const DELETE_MOVIE_RESET = "DELETE_MOVIE_RESET"



export const ADMIN_MOVIE_REQUEST = "ADMIN_MOVIE_REQUEST"
export const ADMIN_MOVIE_SUCCESS = "ADMIN_MOVIE_SUCCESS"
export const ADMIN_MOVIE_FAIL = "ADMIN_MOVIE_FAIL"


export const MOVIE_DETAILS_REQUEST = "MOVIE_DETAILS_REQUEST"
export const MOVIE_DETAILS_SUCCESS = "MOVIE_DETAILS_SUCCESS"
export const MOVIE_DETAILS_FAIL = "MOVIE_DETAILS_FAIL"



export const CLEAR_ERRORS = "CLEAR_ERRORS" 